/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'campaign': RouteRecordInfo<'campaign', '/campaign', Record<never, never>, Record<never, never>>,
    'event-campaign': RouteRecordInfo<'event-campaign', '/eventCampaign', Record<never, never>, Record<never, never>>,
    'hot': RouteRecordInfo<'hot', '/hot', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'setting': RouteRecordInfo<'setting', '/setting', Record<never, never>, Record<never, never>>,
    'watchlist': RouteRecordInfo<'watchlist', '/watchlist', Record<never, never>, Record<never, never>>,
  }
}
